module.exports = {
  "application": [],
  "article": ["article"],
  "banner": ["header"],
  "complementary": ["aside"],
  "contentinfo": ["footer"],
  "directory": [],
  "document": ["body"],
  "form": ["form"],
  "log": [],
  "main": [],
  "navigation": ["nav"],
  "note": [],
  "region": ["div", "frame", "section"],
  "search": [],
  "status": ["output"],
  "alert": [],
  "alertdialog": [],
  "button": ["button", "input[type=\"submit\"]", "input[type=\"reset\"]", "input[type=\"image\"]"],
  "checkbox": ["input[type=\"checkbox\"]"],
  "columnheader": ["th[scope=\"col\"]"],
  "combobox": ["select"],
  "definition": [],
  "dialog": [],
  "directory": [],
  "grid": ["table"],
  "gridcell": ["td"],
  "group": ["fieldset", "optgroup"],
  "heading": ["h1", "h2", "h3", "h4", "h5", "h6", "h7"],
  "img": ["img"],
  "link": ["a[href]", "area"],
  "list": ["ul", "ol"],
  "listbox": ["select", "datalist"],
  "listitem": ["li"],
  "marquee": [],
  "math": [],
  "menu": ["menu[type=\"list\"]"],
  "menubar": [],
  "menuitem": [],
  "menuitemcheckbox": [],
  "menuitemradio": [],
  "option": ["option"],
  "progressbar": ["progress"],
  "radio": ["input[type=\"radio\"]"],
  "radiogroup": [],
  "row": ["tr"],
  "rowgroup": ["thead", "tfoot", "tbody"],
  "rowheader": ["th[scope=\"row\"]"],
  "scrollbar": [],
  "separator": ["hr"],
  "slider": ["input[type=\"range\"]"],
  "spinbutton": [],
  "tab": [],
  "tablist": [],
  "tabpanel": [],
  "textbox": [
    "input[type=\"text\"]",
    "input[type=\"password\"]",
    "input[type=\"email\"]",
    "textarea"
  ],
  "timer": [],
  "toolbar": ["menu[type=\"toolbar\"]"],
  "tooltip": [],
  "tree": [],
  "treegrid": [],
  "treeitem": []
}
